In [7]:
import pandas as pd

In [8]:
data = pd.read_csv("./infos.tsv", sep="\t")
data.columns=['problem', 'model', 'parameter', 'conjure_mode', 'optimization_level', 'heuristic', 'solver', 'var', 'value']
data

,problem,model,parameter,conjure_mode,optimization_level,heuristic,solver,var,value
0,csplib-prob001-CarSequencing,CarSequencing.essence,params/generated/00032000e76ccda5fd02c1d8369f6...,portfolio4,O2,01_compact.eprime,chuffed,SavileRowTimeOut,0.000000e+00
1,csplib-prob001-CarSequencing,CarSequencing.essence,params/generated/00032000e76ccda5fd02c1d8369f6...,portfolio4,O2,01_compact.eprime,chuffed,SavileRowTotalTime,4.164000e+00
2,csplib-prob001-CarSequencing,CarSequencing.essence,params/generated/00032000e76ccda5fd02c1d8369f6...,portfolio4,O2,01_compact.eprime,chuffed,SolverFailures,4.139600e+05
3,csplib-prob001-CarSequencing,CarSequencing.essence,params/generated/00032000e76ccda5fd02c1d8369f6...,portfolio4,O2,01_compact.eprime,chuffed,SolverNodes,6.889080e+05
4,csplib-prob001-CarSequencing,CarSequencing.essence,params/generated/00032000e76ccda5fd02c1d8369f6...,portfolio4,O2,01_compact.eprime,chuffed,SolverSatisfiable,1.000000e+00
...,...,...,...,...,...,...,...,...,...
625818,csplib-prob001-CarSequencing,CarSequencing.essence,params/literature/ReginPuget4.param,portfolio4,O2,06_chPrunedLevels.eprime,kissat,SavileRowClauseOut,0.000000e+00
625819,csplib-prob001-CarSequencing,CarSequencing.essence,params/literature/ReginPuget4.param,portfolio4,O2,06_chPrunedLevels.eprime,kissat,SavileRowTimeOut,0.000000e+00
625820,csplib-prob001-CarSequencing,CarSequencing.essence,params/literature/ReginPuget4.param,portfolio4,O2,06_chPrunedLevels.eprime,kissat,SavileRowTotalTime,2.422000e+00
625821,csplib-prob001-CarSequencing,CarSequencing.essence,params/literature/ReginPuget4.param,portfolio4,O2,06_chPrunedLevels.eprime,kissat,SolverNodes,2.012032e+08
625822,csplib-prob001-CarSequencing,CarSequencing.essence,params/literature/ReginPuget4.param,portfolio4,O2,06_chPrunedLevels.eprime,kissat,SolverTotalTime,3.572200e+03

In [9]:
def transform(data: pd.DataFrame, columns: list)-> pd.DataFrame:
    dict_data = data.to_dict()
    keys = list(dict_data.keys())
    elements = list(dict_data[keys[0]].keys())
    dict_data = [{k: dict_data[k][e] for k in keys} for e in elements] 
    n_elements = len(dict_data)
    i = 0
    grouped = []
    extra_columns = [c for c in keys if c not in columns]
    while i < n_elements:
        current = dict_data[i]
        column_values = [current[c] for c in columns]
        extra = {}
        while column_values == [current[c] for c in columns] and i < n_elements:
            extra[current[extra_columns[0]]] = current[extra_columns[1]]
            i += 1
            if i < n_elements:
                current = dict_data[i]
        new_value = current.copy()
        for c in extra_columns:
            del new_value[c]
        new_value.update(extra)
        grouped.append(new_value)
    return pd.DataFrame(grouped)
            

df = pd.DataFrame(data)
df = transform(df, ['problem', 'model', 'parameter', 'conjure_mode', 'optimization_level', 'heuristic', 'solver'])

In [10]:
df.loc[:,['parameter', 'optimization_level', 'heuristic', 'solver', 'SavileRowTimeOut', 'SavileRowTotalTime', 'SolverFailures', 'SolverNodes', 'SolverSatisfiable', 'SolverTimeOut', 'SolverTotalTime', 'SATClauses', 'SATVars','SavileRowClauseOut', 'SolverMemOut']].isnull().any()

parameter             False
optimization_level    False
heuristic             False
solver                False
SavileRowTimeOut      False
SavileRowTotalTime    False
SolverFailures         True
SolverNodes           False
SolverSatisfiable      True
SolverTimeOut          True
SolverTotalTime       False
SATClauses             True
SATVars                True
SavileRowClauseOut     True
SolverMemOut           True
dtype: bool

In [17]:
non_null_df = df.loc[:,
                     ['parameter', 
                      'optimization_level', 
                      'heuristic', 
                      'solver', 
                      'SavileRowTimeOut', 
                      'SavileRowTotalTime', 
                      'SolverFailures', 
                      'SolverNodes', 
                      'SolverSatisfiable', 
                      'SolverTimeOut', 
                      'SolverTotalTime', 
                      'SATClauses', 
                      'SATVars',
                      'SavileRowClauseOut', 
                      'SolverMemOut']].dropna(axis=1)

In [24]:
non_null_df

,parameter,optimization_level,heuristic,solver,SavileRowTimeOut,SavileRowTotalTime,SolverNodes,SolverTotalTime,TotalTime
0,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,01_compact.eprime,kissat,0.0,4.164,688908.0,45.662,49.826
1,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,02_compact.eprime,chuffed,0.0,5.098,424.0,0.080,5.178
2,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,02_compact.eprime,kissat,0.0,4.292,4378.0,0.343,4.635
3,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,05_nochAllLevels_2.eprime,chuffed,0.0,6.179,339.0,0.050,6.229
4,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,05_nochAllLevels_2.eprime,kissat,0.0,70.339,11399.0,0.101,70.440
...,...,...,...,...,...,...,...,...,...
69541,params/literature/ReginPuget4.param,O2,05_nochAllLevels_2.eprime,chuffed,0.0,3.261,194577775.0,3575.830,3579.091
69542,params/literature/ReginPuget4.param,O2,05_nochAllLevels_2.eprime,kissat,0.0,22.954,43147247.0,3600.140,3623.094
69543,params/literature/ReginPuget4.param,O2,06_chPrunedLevels.eprime,chuffed,0.0,34.462,113254117.0,3577.570,3612.032
69544,params/literature/ReginPuget4.param,O2,06_chPrunedLevels.eprime,kissat,0.0,1.268,40682889.0,3600.075,3601.343
69545,params/literature/ReginPuget4.param,O2,06_chPrunedLevels.eprime,kissat,0.0,2.422,201203166.0,3572.200,3574.622

### My guess is that the values for SolverNodes can be deleted while SavileRowTotalTIme and SOlverTotalTime can be aggregated together into a "TotalTime" variable. The Timeout column can be removed by multiplying by 10 each timeout. The final prediction will be the heuristic + solver option

In [13]:
#Run this to have the dataframe with the correct transfomations already applied

non_null_df = pd.read_csv("./new_data.csv")

In [25]:
def get_total_time(row):
    total_time = row["SolverTotalTime"] + row ["SavileRowTotalTime"]
    if row["SavileRowTimeOut"] == 1:
        total_time *= 10
    return total_time

non_null_df["TotalTime"] = non_null_df.apply(get_total_time, axis=1)
non_null_df

,parameter,optimization_level,heuristic,solver,SavileRowTimeOut,SavileRowTotalTime,SolverNodes,SolverTotalTime,TotalTime
0,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,01_compact.eprime,kissat,0.0,4.164,688908.0,45.662,49.826
1,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,02_compact.eprime,chuffed,0.0,5.098,424.0,0.080,5.178
2,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,02_compact.eprime,kissat,0.0,4.292,4378.0,0.343,4.635
3,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,05_nochAllLevels_2.eprime,chuffed,0.0,6.179,339.0,0.050,6.229
4,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,05_nochAllLevels_2.eprime,kissat,0.0,70.339,11399.0,0.101,70.440
...,...,...,...,...,...,...,...,...,...
69541,params/literature/ReginPuget4.param,O2,05_nochAllLevels_2.eprime,chuffed,0.0,3.261,194577775.0,3575.830,3579.091
69542,params/literature/ReginPuget4.param,O2,05_nochAllLevels_2.eprime,kissat,0.0,22.954,43147247.0,3600.140,3623.094
69543,params/literature/ReginPuget4.param,O2,06_chPrunedLevels.eprime,chuffed,0.0,34.462,113254117.0,3577.570,3612.032
69544,params/literature/ReginPuget4.param,O2,06_chPrunedLevels.eprime,kissat,0.0,1.268,40682889.0,3600.075,3601.343
69545,params/literature/ReginPuget4.param,O2,06_chPrunedLevels.eprime,kissat,0.0,2.422,201203166.0,3572.200,3574.622

In [27]:
def load_file(file_name):
    with open(file_name) as f:
        return f.read()
def get_dataset(df:pd.DataFrame):
    dataset = []
    for i in range(len(df)):
        row = df.iloc[i, :]
        dataset.append({
            "Parameters": load_file(row["parameter"]),
            "OptimizationLevel": row["optimization_level"],
            "Heuristic": row["heuristic"],
            "Solver": row["solver"],
            "Time": row["TotalTime"]
        })
    return dataset

dataset = get_dataset(non_null_df)

In [31]:
from devtools import pprint

In [28]:
dataset[0]

{'Parameters': 'language Essence 1.3\n\nletting blksize_delta be\n        function(1 --> 3, 2 --> 3, 3 --> 3, 4 --> 3, 5 --> 3, 6 --> 3, 7 --> 3, 8 --> 3, 9 --> 3, 10 --> 3, 11 --> 3,\n                 12 --> 3, 13 --> 3, 14 --> 3, 15 --> 3, 16 --> 3, 17 --> 3, 18 --> 3, 19 --> 3)\nletting maxcars be\n        function(1 --> 10, 2 --> 9, 3 --> 6, 4 --> 10, 5 --> 10, 6 --> 10, 7 --> 10, 8 --> 9, 9 --> 10, 10 --> 10,\n                 11 --> 10, 12 --> 10, 13 --> 10, 14 --> 10, 15 --> 10, 16 --> 10, 17 --> 10, 18 --> 10, 19 --> 9)\nletting n_cars be 152\nletting n_classes be 2\nletting n_options be 19\nletting quantity be function(1 --> 76, 2 --> 76)\nletting usage be\n        relation((1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 8), (1, 9), (1, 10), (1, 11), (1, 12), (1, 13),\n                 (1, 14), (1, 15), (1, 16), (1, 17), (1, 18), (2, 7), (2, 19))\n$ Visualisation for usage\n$  1  1\n$  1  2\n$  1  3\n$  1  4\n$  1  5\n$  1  6\n$  1  8\n$  1  9\n$  1 10\n$  1 11\n$  1 12\n$  1 13\n$  1 14\n$  1 15\n$  1 16\n$  1 17\n$  1 18\n$  2  7\n$  2 19\n\n',
 'OptimizationLevel': 'O2',
 'Heuristic': '01_compact.eprime',
 'Solver': 'kissat',
 'Time': 49.826}

In [34]:
def make_stats(df:pd.DataFrame, aggregate_on:list, plot_value_name:str, plot_column:str)-> None:
    plot_dict = {}
    for i in range(len(df)):
        row = df.iloc[i, :]
        key = "_".join([str(row[column]) for column in aggregate_on])
        if key not in plot_dict:
            plot_dict[key] = {}
        plot_dict[key][row[plot_value_name]] = row[plot_column]
    return plot_dict

plt_dict = make_stats(non_null_df, ["parameter", "optimization_level", "heuristic"], "solver", "TotalTime")

In [35]:
list(plt_dict.keys())

['params/generated/00032000e76ccda5fd02c1d8369f6fa7.param_O2_01_compact.eprime',
 'params/generated/00032000e76ccda5fd02c1d8369f6fa7.param_O2_02_compact.eprime',
 'params/generated/00032000e76ccda5fd02c1d8369f6fa7.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/00032000e76ccda5fd02c1d8369f6fa7.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00078694bd51565b6a59a77ac27a3372.param_O2_01_compact.eprime',
 'params/generated/00078694bd51565b6a59a77ac27a3372.param_O2_02_compact.eprime',
 'params/generated/00078694bd51565b6a59a77ac27a3372.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/00078694bd51565b6a59a77ac27a3372.param_O2_06_chPrunedLevels.eprime',
 'params/generated/000a25d0e08853f125c4c81ad92527ec.param_O2_01_compact.eprime',
 'params/generated/000a25d0e08853f125c4c81ad92527ec.param_O2_02_compact.eprime',
 'params/generated/000a25d0e08853f125c4c81ad92527ec.param_O2_06_chPrunedLevels.eprime',
 'params/generated/001253c5c9fbb8c19491995ea1004b72.param_O2_01_compact.eprime',
 'params/generated/001253c5c9fbb8c19491995ea1004b72.param_O2_02_compact.eprime',
 'params/generated/001253c5c9fbb8c19491995ea1004b72.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00178ba21a2ad74d0814c3744e18d227.param_O2_01_compact.eprime',
 'params/generated/00178ba21a2ad74d0814c3744e18d227.param_O2_02_compact.eprime',
 'params/generated/00178ba21a2ad74d0814c3744e18d227.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/00178ba21a2ad74d0814c3744e18d227.param_O2_06_chPrunedLevels.eprime',
 'params/generated/0019bb159c95d96e9c0e5bcd7ccc2c57.param_O2_01_compact.eprime',
 'params/generated/0019bb159c95d96e9c0e5bcd7ccc2c57.param_O2_02_compact.eprime',
 'params/generated/0019bb159c95d96e9c0e5bcd7ccc2c57.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00201d488826e84ec9a49cfd5fd31207.param_O2_01_compact.eprime',
 'params/generated/00201d488826e84ec9a49cfd5fd31207.param_O2_02_compact.eprime',
 'params/generated/00201d488826e84ec9a49cfd5fd31207.param_O2_06_chPrunedLevels.eprime',
 'params/generated/002f225b32b951af0b14c29d93ff9348.param_O2_01_compact.eprime',
 'params/generated/002f225b32b951af0b14c29d93ff9348.param_O2_02_compact.eprime',
 'params/generated/002f225b32b951af0b14c29d93ff9348.param_O2_06_chPrunedLevels.eprime',
 'params/generated/003fdfe3ec3b109ddf4ee4b64e9953fd.param_O2_01_compact.eprime',
 'params/generated/003fdfe3ec3b109ddf4ee4b64e9953fd.param_O2_02_compact.eprime',
 'params/generated/003fdfe3ec3b109ddf4ee4b64e9953fd.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/003fdfe3ec3b109ddf4ee4b64e9953fd.param_O2_06_chPrunedLevels.eprime',
 'params/generated/0041462199c3efeee8d75b1e7c58d281.param_O2_01_compact.eprime',
 'params/generated/0041462199c3efeee8d75b1e7c58d281.param_O2_02_compact.eprime',
 'params/generated/0041462199c3efeee8d75b1e7c58d281.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/0041462199c3efeee8d75b1e7c58d281.param_O2_06_chPrunedLevels.eprime',
 'params/generated/004212a3973aa110d140a382edc13695.param_O2_01_compact.eprime',
 'params/generated/004212a3973aa110d140a382edc13695.param_O2_02_compact.eprime',
 'params/generated/004212a3973aa110d140a382edc13695.param_O2_06_chPrunedLevels.eprime',
 'params/generated/004e247a2657a80880010f347b2558d2.param_O2_01_compact.eprime',
 'params/generated/004e247a2657a80880010f347b2558d2.param_O2_02_compact.eprime',
 'params/generated/004e247a2657a80880010f347b2558d2.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00557d07199f73c7b3b8cdedc19c4a56.param_O2_01_compact.eprime',
 'params/generated/00557d07199f73c7b3b8cdedc19c4a56.param_O2_02_compact.eprime',
 'params/generated/00557d07199f73c7b3b8cdedc19c4a56.param_O2_06_chPrunedLevels.eprime',
 'params/generated/005634e7654e8a21e2c90a2f2e545ab8.param_O2_01_compact.eprime',
 'params/generated/005634e7654e8a21e2c90a2f2e545ab8.param_O2_02_compact.eprime',
 'params/generated/005634e7654e8a21e2c90a2f2e545ab8.param_O2_06_chPrunedLevels.eprime',
 'params/generated/005de4e641b1a31b5a79f20b980525d0.param_O2_01_compact.eprime',
 'params/generated/005de4e641b1a31b5a79f20b980525d0.param_O2_02_compact.eprime',
 'params/generated/005de4e641b1a31b5a79f20b980525d0.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/005de4e641b1a31b5a79f20b980525d0.param_O2_06_chPrunedLevels.eprime',
 'params/generated/005e39c03b57a76a7281e5e61048073e.param_O2_01_compact.eprime',
 'params/generated/005e39c03b57a76a7281e5e61048073e.param_O2_02_compact.eprime',
 'params/generated/005e39c03b57a76a7281e5e61048073e.param_O2_06_chPrunedLevels.eprime',
 'params/generated/006203abbde04765b8c95369423cc635.param_O2_01_compact.eprime',
 'params/generated/006203abbde04765b8c95369423cc635.param_O2_02_compact.eprime',
 'params/generated/006203abbde04765b8c95369423cc635.param_O2_06_chPrunedLevels.eprime',
 'params/generated/006cc2b3e48b9329f08b7e47ef56414e.param_O2_01_compact.eprime',
 'params/generated/006cc2b3e48b9329f08b7e47ef56414e.param_O2_02_compact.eprime',
 'params/generated/006cc2b3e48b9329f08b7e47ef56414e.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/006cc2b3e48b9329f08b7e47ef56414e.param_O2_06_chPrunedLevels.eprime',
 'params/generated/006fc7396713e6da78b863a6cf3ad6cc.param_O2_01_compact.eprime',
 'params/generated/006fc7396713e6da78b863a6cf3ad6cc.param_O2_02_compact.eprime',
 'params/generated/006fc7396713e6da78b863a6cf3ad6cc.param_O2_06_chPrunedLevels.eprime',
 'params/generated/0072c4d42b11b0b9fda42283b7a1f4c0.param_O2_01_compact.eprime',
 'params/generated/0072c4d42b11b0b9fda42283b7a1f4c0.param_O2_02_compact.eprime',
 'params/generated/0072c4d42b11b0b9fda42283b7a1f4c0.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/0072c4d42b11b0b9fda42283b7a1f4c0.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00759f6523247017775305e891d7732f.param_O2_01_compact.eprime',
 'params/generated/00759f6523247017775305e891d7732f.param_O2_02_compact.eprime',
 'params/generated/00759f6523247017775305e891d7732f.param_O2_06_chPrunedLevels.eprime',
 'params/generated/007b2b841705dbba3f4b4097ccdb637c.param_O2_01_compact.eprime',
 'params/generated/007b2b841705dbba3f4b4097ccdb637c.param_O2_02_compact.eprime',
 'params/generated/007b2b841705dbba3f4b4097ccdb637c.param_O2_06_chPrunedLevels.eprime',
 'params/generated/007b4d84d6a068334c7a746f0f59ff0d.param_O2_01_compact.eprime',
 'params/generated/007b4d84d6a068334c7a746f0f59ff0d.param_O2_02_compact.eprime',
 'params/generated/007b4d84d6a068334c7a746f0f59ff0d.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/007b4d84d6a068334c7a746f0f59ff0d.param_O2_06_chPrunedLevels.eprime',
 'params/generated/0081e9e626f4b949373e408d45cf6475.param_O2_01_compact.eprime',
 'params/generated/0081e9e626f4b949373e408d45cf6475.param_O2_02_compact.eprime',
 'params/generated/0081e9e626f4b949373e408d45cf6475.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/0081e9e626f4b949373e408d45cf6475.param_O2_06_chPrunedLevels.eprime',
 'params/generated/008791fd87c804b4860f3ade1ee17532.param_O2_01_compact.eprime',
 'params/generated/008791fd87c804b4860f3ade1ee17532.param_O2_02_compact.eprime',
 'params/generated/008791fd87c804b4860f3ade1ee17532.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/008791fd87c804b4860f3ade1ee17532.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00924ade2d9f8c44091295fd2698cf60.param_O2_01_compact.eprime',
 'params/generated/00924ade2d9f8c44091295fd2698cf60.param_O2_02_compact.eprime',
 'params/generated/00924ade2d9f8c44091295fd2698cf60.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/00924ade2d9f8c44091295fd2698cf60.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00997e552cf26a843d73a61467e37e72.param_O2_01_compact.eprime',
 'params/generated/00997e552cf26a843d73a61467e37e72.param_O2_02_compact.eprime',
 'params/generated/00997e552cf26a843d73a61467e37e72.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00b14d141ef8a02f8f1068e0c1ac7885.param_O2_01_compact.eprime',
 'params/generated/00b14d141ef8a02f8f1068e0c1ac7885.param_O2_02_compact.eprime',
 'params/generated/00b14d141ef8a02f8f1068e0c1ac7885.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00b1f58f19b16b3d782198b69ba26bed.param_O2_01_compact.eprime',
 'params/generated/00b1f58f19b16b3d782198b69ba26bed.param_O2_02_compact.eprime',
 'params/generated/00b1f58f19b16b3d782198b69ba26bed.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/00b1f58f19b16b3d782198b69ba26bed.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00b934d1e58340b906c5fa6ba3525a26.param_O2_01_compact.eprime',
 'params/generated/00b934d1e58340b906c5fa6ba3525a26.param_O2_02_compact.eprime',
 'params/generated/00b934d1e58340b906c5fa6ba3525a26.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00c33ec0ff0a6db86a8acfdf80fbda47.param_O2_01_compact.eprime',
 'params/generated/00c33ec0ff0a6db86a8acfdf80fbda47.param_O2_02_compact.eprime',
 'params/generated/00c33ec0ff0a6db86a8acfdf80fbda47.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00c5987f6739c6c78cb2353e847cb389.param_O2_01_compact.eprime',
 'params/generated/00c5987f6739c6c78cb2353e847cb389.param_O2_02_compact.eprime',
 'params/generated/00c5987f6739c6c78cb2353e847cb389.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/00c5987f6739c6c78cb2353e847cb389.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00c5a7b30ddd11902daff089693dcf11.param_O2_01_compact.eprime',
 'params/generated/00c5a7b30ddd11902daff089693dcf11.param_O2_02_compact.eprime',
 'params/generated/00c5a7b30ddd11902daff089693dcf11.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00d703f92d6d1ed045270ede5f342ce9.param_O2_01_compact.eprime',
 'params/generated/00d703f92d6d1ed045270ede5f342ce9.param_O2_02_compact.eprime',
 'params/generated/00d703f92d6d1ed045270ede5f342ce9.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/00d703f92d6d1ed045270ede5f342ce9.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00e4b10a111cc5f8696f9391b017dd83.param_O2_01_compact.eprime',
 'params/generated/00e4b10a111cc5f8696f9391b017dd83.param_O2_02_compact.eprime',
 'params/generated/00e4b10a111cc5f8696f9391b017dd83.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/00e4b10a111cc5f8696f9391b017dd83.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00e645b22c0b9680a698a27993d981b1.param_O2_01_compact.eprime',
 'params/generated/00e645b22c0b9680a698a27993d981b1.param_O2_02_compact.eprime',
 'params/generated/00e645b22c0b9680a698a27993d981b1.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00eb20d3f1c256d747b5f9510a81a0e4.param_O2_01_compact.eprime',
 'params/generated/00eb20d3f1c256d747b5f9510a81a0e4.param_O2_02_compact.eprime',
 'params/generated/00eb20d3f1c256d747b5f9510a81a0e4.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/00eb20d3f1c256d747b5f9510a81a0e4.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00f3729761ae0fb2ee01debaeeb18eb2.param_O2_01_compact.eprime',
 'params/generated/00f3729761ae0fb2ee01debaeeb18eb2.param_O2_02_compact.eprime',
 'params/generated/00f3729761ae0fb2ee01debaeeb18eb2.param_O2_06_chPrunedLevels.eprime',
 'params/generated/00f3e31a4c0c325679c0bdbb6aacdc60.param_O2_01_compact.eprime',
 'params/generated/00f3e31a4c0c325679c0bdbb6aacdc60.param_O2_02_compact.eprime',
 'params/generated/00f3e31a4c0c325679c0bdbb6aacdc60.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/00f3e31a4c0c325679c0bdbb6aacdc60.param_O2_06_chPrunedLevels.eprime',
 'params/generated/01018c8ac7fbfeddd62e7e9a102d13d4.param_O2_01_compact.eprime',
 'params/generated/01018c8ac7fbfeddd62e7e9a102d13d4.param_O2_02_compact.eprime',
 'params/generated/01018c8ac7fbfeddd62e7e9a102d13d4.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/01018c8ac7fbfeddd62e7e9a102d13d4.param_O2_06_chPrunedLevels.eprime',
 'params/generated/010bf1478cd24c3c9e0d9de8a5026436.param_O2_01_compact.eprime',
 'params/generated/010bf1478cd24c3c9e0d9de8a5026436.param_O2_02_compact.eprime',
 'params/generated/010bf1478cd24c3c9e0d9de8a5026436.param_O2_06_chPrunedLevels.eprime',
 'params/generated/0110b47319a2510b544ce98f96f5d478.param_O2_01_compact.eprime',
 'params/generated/0110b47319a2510b544ce98f96f5d478.param_O2_02_compact.eprime',
 'params/generated/0110b47319a2510b544ce98f96f5d478.param_O2_06_chPrunedLevels.eprime',
 'params/generated/01191e69afb84ecc57dc67f20192aef8.param_O2_01_compact.eprime',
 'params/generated/01191e69afb84ecc57dc67f20192aef8.param_O2_02_compact.eprime',
 'params/generated/01191e69afb84ecc57dc67f20192aef8.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/01191e69afb84ecc57dc67f20192aef8.param_O2_06_chPrunedLevels.eprime',
 'params/generated/01198b222ba938c67954a881c2403ce4.param_O2_01_compact.eprime',
 'params/generated/01198b222ba938c67954a881c2403ce4.param_O2_02_compact.eprime',
 'params/generated/01198b222ba938c67954a881c2403ce4.param_O2_06_chPrunedLevels.eprime',
 'params/generated/0119cb448071ca8fdcce8522a30c8334.param_O2_01_compact.eprime',
 'params/generated/0119cb448071ca8fdcce8522a30c8334.param_O2_02_compact.eprime',
 'params/generated/0119cb448071ca8fdcce8522a30c8334.param_O2_06_chPrunedLevels.eprime',
 'params/generated/011dcd88cea17f28777acfc533dc2789.param_O2_01_compact.eprime',
 'params/generated/011dcd88cea17f28777acfc533dc2789.param_O2_02_compact.eprime',
 'params/generated/011dcd88cea17f28777acfc533dc2789.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/011dcd88cea17f28777acfc533dc2789.param_O2_06_chPrunedLevels.eprime',
 'params/generated/01208f3c4cd6a01be9ac85eec215ccce.param_O2_01_compact.eprime',
 'params/generated/01208f3c4cd6a01be9ac85eec215ccce.param_O2_02_compact.eprime',
 'params/generated/01208f3c4cd6a01be9ac85eec215ccce.param_O2_06_chPrunedLevels.eprime',
 'params/generated/012404a51b522790a6c09999aa738c79.param_O2_01_compact.eprime',
 'params/generated/012404a51b522790a6c09999aa738c79.param_O2_02_compact.eprime',
 'params/generated/012404a51b522790a6c09999aa738c79.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/012404a51b522790a6c09999aa738c79.param_O2_06_chPrunedLevels.eprime',
 'params/generated/0125066f38d58b69c861d5b967831101.param_O2_01_compact.eprime',
 'params/generated/0125066f38d58b69c861d5b967831101.param_O2_02_compact.eprime',
 'params/generated/0125066f38d58b69c861d5b967831101.param_O2_06_chPrunedLevels.eprime',
 'params/generated/0125af1642524ece15814851ea2daad4.param_O2_01_compact.eprime',
 'params/generated/0125af1642524ece15814851ea2daad4.param_O2_02_compact.eprime',
 'params/generated/0125af1642524ece15814851ea2daad4.param_O2_06_chPrunedLevels.eprime',
 'params/generated/01297b26763f17a65130763079140e17.param_O2_01_compact.eprime',
 'params/generated/01297b26763f17a65130763079140e17.param_O2_02_compact.eprime',
 'params/generated/01297b26763f17a65130763079140e17.param_O2_06_chPrunedLevels.eprime',
 'params/generated/012af2a3d5f43a27e570f35101b27c5d.param_O2_01_compact.eprime',
 'params/generated/012af2a3d5f43a27e570f35101b27c5d.param_O2_02_compact.eprime',
 'params/generated/012af2a3d5f43a27e570f35101b27c5d.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/012af2a3d5f43a27e570f35101b27c5d.param_O2_06_chPrunedLevels.eprime',
 'params/generated/012ebac96ae7c942b063e0b9c256c18e.param_O2_01_compact.eprime',
 'params/generated/012ebac96ae7c942b063e0b9c256c18e.param_O2_02_compact.eprime',
 'params/generated/012ebac96ae7c942b063e0b9c256c18e.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/012ebac96ae7c942b063e0b9c256c18e.param_O2_06_chPrunedLevels.eprime',
 'params/generated/013430a8e674fe0976bdbf3d418b3ce4.param_O2_01_compact.eprime',
 'params/generated/013430a8e674fe0976bdbf3d418b3ce4.param_O2_02_compact.eprime',
 'params/generated/013430a8e674fe0976bdbf3d418b3ce4.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/013430a8e674fe0976bdbf3d418b3ce4.param_O2_06_chPrunedLevels.eprime',
 'params/generated/0134e661a15fc9aab57f2f13fb2056f7.param_O2_01_compact.eprime',
 'params/generated/0134e661a15fc9aab57f2f13fb2056f7.param_O2_02_compact.eprime',
 'params/generated/0134e661a15fc9aab57f2f13fb2056f7.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/0134e661a15fc9aab57f2f13fb2056f7.param_O2_06_chPrunedLevels.eprime',
 'params/generated/0140a1e0bc910da1723859f0ffbea7cb.param_O2_01_compact.eprime',
 'params/generated/0140a1e0bc910da1723859f0ffbea7cb.param_O2_02_compact.eprime',
 'params/generated/0140a1e0bc910da1723859f0ffbea7cb.param_O2_06_chPrunedLevels.eprime',
 'params/generated/014381a492bca39e02494ca20754f869.param_O2_01_compact.eprime',
 'params/generated/014381a492bca39e02494ca20754f869.param_O2_02_compact.eprime',
 'params/generated/014381a492bca39e02494ca20754f869.param_O2_06_chPrunedLevels.eprime',
 'params/generated/014ee93a427ce02d701980478ace39b3.param_O2_01_compact.eprime',
 'params/generated/014ee93a427ce02d701980478ace39b3.param_O2_02_compact.eprime',
 'params/generated/014ee93a427ce02d701980478ace39b3.param_O2_06_chPrunedLevels.eprime',
 'params/generated/0165013899ae782e51b61c5c1c6987df.param_O2_01_compact.eprime',
 'params/generated/0165013899ae782e51b61c5c1c6987df.param_O2_02_compact.eprime',
 'params/generated/0165013899ae782e51b61c5c1c6987df.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/0165013899ae782e51b61c5c1c6987df.param_O2_06_chPrunedLevels.eprime',
 'params/generated/017122e459ec7ef357f72c3c7f33e769.param_O2_01_compact.eprime',
 'params/generated/017122e459ec7ef357f72c3c7f33e769.param_O2_02_compact.eprime',
 'params/generated/017122e459ec7ef357f72c3c7f33e769.param_O2_06_chPrunedLevels.eprime',
 'params/generated/0174f99e960c5a6d55d3dbad71c09676.param_O2_01_compact.eprime',
 'params/generated/0174f99e960c5a6d55d3dbad71c09676.param_O2_02_compact.eprime',
 'params/generated/0174f99e960c5a6d55d3dbad71c09676.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/0174f99e960c5a6d55d3dbad71c09676.param_O2_06_chPrunedLevels.eprime',
 'params/generated/017eadbb16b3c85a8a4abebc34f3b625.param_O2_01_compact.eprime',
 'params/generated/017eadbb16b3c85a8a4abebc34f3b625.param_O2_02_compact.eprime',
 'params/generated/017eadbb16b3c85a8a4abebc34f3b625.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/017eadbb16b3c85a8a4abebc34f3b625.param_O2_06_chPrunedLevels.eprime',
 'params/generated/017f007034660000b355f0fec7486ed4.param_O2_01_compact.eprime',
 'params/generated/017f007034660000b355f0fec7486ed4.param_O2_02_compact.eprime',
 'params/generated/017f007034660000b355f0fec7486ed4.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/017f007034660000b355f0fec7486ed4.param_O2_06_chPrunedLevels.eprime',
 'params/generated/017f74bd0994d0dc5b6c2739b5efe62b.param_O2_01_compact.eprime',
 'params/generated/017f74bd0994d0dc5b6c2739b5efe62b.param_O2_02_compact.eprime',
 'params/generated/017f74bd0994d0dc5b6c2739b5efe62b.param_O2_06_chPrunedLevels.eprime',
 'params/generated/018880091885a993ddc8de5a59785986.param_O2_01_compact.eprime',
 'params/generated/018880091885a993ddc8de5a59785986.param_O2_02_compact.eprime',
 'params/generated/018880091885a993ddc8de5a59785986.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/018880091885a993ddc8de5a59785986.param_O2_06_chPrunedLevels.eprime',
 'params/generated/018acd5340b370b9f3c6d804a2347c6c.param_O2_01_compact.eprime',
 'params/generated/018acd5340b370b9f3c6d804a2347c6c.param_O2_02_compact.eprime',
 'params/generated/018acd5340b370b9f3c6d804a2347c6c.param_O2_05_nochAllLevels_2.eprime',
 'params/generated/018acd5340b370b9f3c6d804a2347c6c.param_O2_06_chPrunedLevels.eprime',
 'params/generated/018b4bf6b4789d2d42a69d943d2e9af9.param_O2_01_compact.eprime',
 'params/generated/018b4bf6b4789d2d42a69d943d2e9af9.param_O2_02_compact.eprime',
 'params/generated/018b4bf6b4789d2d42a69d943d2e9af9.param_O2_06_chPrunedLevels.eprime',
 'params/generated/018f9f5db48892c329c3095edd6248f5.param_O2_01_compact.eprime',
 'params/generated/018f9f5db48892c329c3095edd6248f5.param_O2_02_compact.eprime',
 'params/generated/018f9f5db48892c329c3095edd6248f5.param_O2_06_chPrunedLevels.eprime',
 'params/generated/018fbdf4a81a0f8dafd2a09ed0659975.param_O2_01_compact.eprime',

In [2]:
from transformers import BertTokenizer, BertModel
import torch.nn as nn
import torch
from typing import Tuple, Literal
from sys import stdout

In [3]:
class NeuralNetwork(nn.Module):
  """
  This class implements a simple interface to get a working neural network using pytorch.
  """
  def __init__(self) -> None:
     super().__init__()
  def train_network(self,
            train_loader:torch.utils.data.DataLoader,
            validation_loader:torch.utils.data.DataLoader,
            optimizer = torch.optim.Adam, 
            loss_function = nn.CrossEntropyLoss(),
            learning_rate:float=.1,
            epochs:int=10,
            device:str='cpu',
            output_extraction_function:callable = lambda x: torch.round(x).detach().cpu(),
            metrics:dict[str,callable] = {},
            verbose:bool=False,
            automatically_handle_gpu_memory:bool = True) -> Tuple[dict[str,list[float]],dict[str,list[float]]]:
    """
      A simple training loop for the neural network. It returns the epochs loss and accuracy history both on the training and the validation set. The tuple will be formatted as:
      train loss, train accuracy, val loss, val accuracy
      Parameters
      ----------
      train_loader: torch.utils.data.DataLoader
        A dataloader containing the dataset that will be used for training the network
      validation_loader: torch.utils.data.DataLoader
        A dataloader containing the dataset that will be used for validate the network at the end of each epoch
      optimizer:
        The optimizer to use while training, default to Adam.
      loss_function:
        The loss function to use while training, default to crossentropy
      learning_rate: float
        The learning rate that will be used in the optimizer to train the network. Default to .1
      epochs: int
        The number of training epochs, default to 10.
      device: str
        The device to use for the computation
      metrics: dict[str,callable]
        The metrics to use to evaluate the network
      verbose: bool
        Determines if intermidiate values of training statistics will be printed to stdout
      automatically_handle_gpu_memory: bool
        Determines if the training function should handle the moving of the data from e to the gpu memory (both the model and the training/validation data)
    """
    old_device = next(self.parameters()).device
    if next(self.parameters()).device == device or not automatically_handle_gpu_memory:
      net = self
    else:
      net = self.to(device)
    optimizer = optimizer(net.parameters(), learning_rate)

    train_loss_history = []
    val_loss_history = []

    total_batch = int(len(train_loader.dataset) / train_loader.batch_size)
    train_metrics_scores = {}
    val_metrics_scores = {}
    for key in metrics:
        train_metrics_scores[key] = []
        val_metrics_scores[key] = []

    for epoch in range(epochs):
        net.train()
        for batch_idx, data in enumerate(train_loader):
            labels = data[1]
            inputs = data[0]
            if automatically_handle_gpu_memory:
              labels = data[1].to(device)
              inputs = self.__to(data[0], device)
            outputs = net(inputs)
            loss = loss_function(outputs, labels)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            predicted_classes = output_extraction_function(outputs)
            normal_labels = output_extraction_function(labels)
            if verbose:
              stdout.write(f"\rbatch {batch_idx + 1}/{total_batch} ----- loss: {loss.cpu()} ----- {'-----'.join([f'{key}: {metrics[key](predicted_classes, normal_labels)}' for key in metrics.keys()])}")
              stdout.flush()
            if automatically_handle_gpu_memory:
              self.__remove(inputs)
              del labels
              torch.cuda.empty_cache()

        val_metrics, val_loss = self.__validate(validation_loader, metrics, loss_function, device, output_extraction_function, automatically_handle_gpu_memory)
        for key in metrics:
          val_metrics_scores[key].append(val_metrics[key])
        val_loss_history.append(val_loss)
        train_metrics, train_loss = self.__validate(train_loader, metrics, loss_function, device, output_extraction_function, automatically_handle_gpu_memory)
        for key in metrics:
          train_metrics_scores[key].append(train_metrics[key])
        train_loss_history.append(train_loss)
        if verbose:
          out_str = f"EPOCH {epoch + 1} training loss: {train_loss_history[-1]} - validation loss: {val_loss_history[-1]}\n" + \
          '\n'.join([f"EPOCH {epoch + 1} training {metric}: {train_metrics_scores[metric][-1]} - validation {metric}: {val_metrics_scores[metric][-1]}" for metric in metrics.keys()]) +\
          f"\n{'-'*100}\n"
          stdout.write("\r" + " " * len(out_str) + "\r")
          stdout.flush()
          stdout.write(out_str)
          stdout.flush()
          print()
    train_metrics_scores['loss'] = train_loss_history
    val_metrics_scores['loss'] = val_loss_history

    if next(self.parameters()).device != old_device and automatically_handle_gpu_memory:
      del net
      self = self.to(old_device)
      torch.cuda.empty_cache()

    return train_metrics_scores, val_metrics_scores
  
  def __to(self, data, device):
    if isinstance(data, dict):
      return {key: self.__to(data[key], device) for key in data.keys()}
    elif isinstance(data, list):
      return [self.__to(d, device) for d in data]
    elif isinstance(data, tuple):
      return tuple([self.__to(d, device) for d in data])
    else:
      return data.to(device)
    
  def __remove(self, data):
    if isinstance(data, dict):
      for key in data.keys():
        self.__remove(data[key])
    elif isinstance(data, list) or isinstance(data, tuple):
      for d in data:
        self.__remove(d)
    else:
      del data

  def __validate(self, loader, metrics, loss_function, device, output_extraction_function, automatically_handle_gpu_memory):
    losses = []
    metrics_scores = {}
    for key in metrics.keys():
      metrics_scores[key] = []
    net = self.to(device)
    net.eval()
    with torch.no_grad():
        for batch_idx, data in enumerate(loader):
          labels = data[1]
          inputs = data[0]
          if automatically_handle_gpu_memory:
            inputs = self.__to(data[0], device)
            labels = data[1].to(device)
          outputs = net(inputs)
          loss = loss_function(outputs, labels)
          losses.append(loss)
          predicted_classes = output_extraction_function(outputs)
          real_labels = output_extraction_function(labels)
          for key in metrics.keys():
            metrics_scores[key].append(metrics[key](predicted_classes, real_labels))
          if automatically_handle_gpu_memory:
            self.__remove(inputs)
            del labels
            torch.cuda.empty_cache()

    average_loss = sum(losses)/(batch_idx+1)
    mean_metrics_scores = {}
    for key in metrics.keys():
      mean_metrics_scores[key] = sum(metrics_scores[key])/len(loader)
    return mean_metrics_scores, average_loss