In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("./infos.tsv", sep="\t")
data.columns=['problem', 'model', 'parameter', 'conjure_mode', 'optimization_level', 'heuristic', 'solver', 'var', 'value']
data

,problem,model,parameter,conjure_mode,optimization_level,heuristic,solver,var,value
0,csplib-prob001-CarSequencing,CarSequencing.essence,params/generated/00032000e76ccda5fd02c1d8369f6...,portfolio4,O2,01_compact.eprime,chuffed,SavileRowTimeOut,0.000000e+00
1,csplib-prob001-CarSequencing,CarSequencing.essence,params/generated/00032000e76ccda5fd02c1d8369f6...,portfolio4,O2,01_compact.eprime,chuffed,SavileRowTotalTime,4.164000e+00
2,csplib-prob001-CarSequencing,CarSequencing.essence,params/generated/00032000e76ccda5fd02c1d8369f6...,portfolio4,O2,01_compact.eprime,chuffed,SolverFailures,4.139600e+05
3,csplib-prob001-CarSequencing,CarSequencing.essence,params/generated/00032000e76ccda5fd02c1d8369f6...,portfolio4,O2,01_compact.eprime,chuffed,SolverNodes,6.889080e+05
4,csplib-prob001-CarSequencing,CarSequencing.essence,params/generated/00032000e76ccda5fd02c1d8369f6...,portfolio4,O2,01_compact.eprime,chuffed,SolverSatisfiable,1.000000e+00
...,...,...,...,...,...,...,...,...,...
625818,csplib-prob001-CarSequencing,CarSequencing.essence,params/literature/ReginPuget4.param,portfolio4,O2,06_chPrunedLevels.eprime,kissat,SavileRowClauseOut,0.000000e+00
625819,csplib-prob001-CarSequencing,CarSequencing.essence,params/literature/ReginPuget4.param,portfolio4,O2,06_chPrunedLevels.eprime,kissat,SavileRowTimeOut,0.000000e+00
625820,csplib-prob001-CarSequencing,CarSequencing.essence,params/literature/ReginPuget4.param,portfolio4,O2,06_chPrunedLevels.eprime,kissat,SavileRowTotalTime,2.422000e+00
625821,csplib-prob001-CarSequencing,CarSequencing.essence,params/literature/ReginPuget4.param,portfolio4,O2,06_chPrunedLevels.eprime,kissat,SolverNodes,2.012032e+08
625822,csplib-prob001-CarSequencing,CarSequencing.essence,params/literature/ReginPuget4.param,portfolio4,O2,06_chPrunedLevels.eprime,kissat,SolverTotalTime,3.572200e+03

In [4]:
def transform(data: pd.DataFrame, columns: list)-> pd.DataFrame:
    dict_data = data.to_dict()
    keys = list(dict_data.keys())
    elements = list(dict_data[keys[0]].keys())
    dict_data = [{k: dict_data[k][e] for k in keys} for e in elements] 
    n_elements = len(dict_data)
    i = 0
    grouped = []
    extra_columns = [c for c in keys if c not in columns]
    while i < n_elements:
        current = dict_data[i]
        column_values = [current[c] for c in columns]
        extra = {}
        while column_values == [current[c] for c in columns] and i < n_elements:
            extra[current[extra_columns[0]]] = current[extra_columns[1]]
            i += 1
            if i < n_elements:
                current = dict_data[i]
        new_value = current.copy()
        for c in extra_columns:
            del new_value[c]
        new_value.update(extra)
        grouped.append(new_value)
    return pd.DataFrame(grouped)
            

df = pd.DataFrame(data)
df = transform(df, ['problem', 'model', 'parameter', 'conjure_mode', 'optimization_level', 'heuristic', 'solver'])

In [5]:
df.loc[:,['parameter', 'optimization_level', 'heuristic', 'solver', 'SavileRowTimeOut', 'SavileRowTotalTime', 'SolverFailures', 'SolverNodes', 'SolverSatisfiable', 'SolverTimeOut', 'SolverTotalTime', 'SATClauses', 'SATVars','SavileRowClauseOut', 'SolverMemOut']].isnull().any()

parameter             False
optimization_level    False
heuristic             False
solver                False
SavileRowTimeOut      False
SavileRowTotalTime    False
SolverFailures         True
SolverNodes           False
SolverSatisfiable      True
SolverTimeOut          True
SolverTotalTime       False
SATClauses             True
SATVars                True
SavileRowClauseOut     True
SolverMemOut           True
dtype: bool

In [23]:
non_null_df = df.loc[:,
                     ['parameter', 
                      'optimization_level', 
                      'heuristic', 
                      'solver', 
                      'SavileRowTimeOut', 
                      'SavileRowTotalTime', 
                      'SolverFailures', 
                      'SolverNodes', 
                      'SolverSatisfiable', 
                      'SolverTimeOut', 
                      'SolverTotalTime', 
                      'SATClauses', 
                      'SATVars',
                      'SavileRowClauseOut', 
                      'SolverMemOut']].dropna(axis=1)

In [24]:
non_null_df

,parameter,optimization_level,heuristic,solver,SavileRowTimeOut,SavileRowTotalTime,SolverNodes,SolverTotalTime
0,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,01_compact.eprime,kissat,0.0,4.164,688908.0,45.662
1,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,02_compact.eprime,chuffed,0.0,5.098,424.0,0.080
2,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,02_compact.eprime,kissat,0.0,4.292,4378.0,0.343
3,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,05_nochAllLevels_2.eprime,chuffed,0.0,6.179,339.0,0.050
4,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,05_nochAllLevels_2.eprime,kissat,0.0,70.339,11399.0,0.101
...,...,...,...,...,...,...,...,...
69541,params/literature/ReginPuget4.param,O2,05_nochAllLevels_2.eprime,chuffed,0.0,3.261,194577775.0,3575.830
69542,params/literature/ReginPuget4.param,O2,05_nochAllLevels_2.eprime,kissat,0.0,22.954,43147247.0,3600.140
69543,params/literature/ReginPuget4.param,O2,06_chPrunedLevels.eprime,chuffed,0.0,34.462,113254117.0,3577.570
69544,params/literature/ReginPuget4.param,O2,06_chPrunedLevels.eprime,kissat,0.0,1.268,40682889.0,3600.075
69545,params/literature/ReginPuget4.param,O2,06_chPrunedLevels.eprime,kissat,0.0,2.422,201203166.0,3572.200

### My guess is that the values for SolverNodes can be deleted while SavileRowTotalTIme and SOlverTotalTime can be aggregated together into a "TotalTime" variable. The Timeout column can be removed by multiplying by 10 each timeout. The final prediction will be the heuristic + solver option

In [34]:
#Run this to have the dataframe with the correct transfomations already applied

non_null_df = pd.read_csv("./new_data.csv")

In [27]:
def get_total_time(row):
    total_time = row["SolverTotalTime"] + row ["SavileRowTotalTime"]
    if row["SavileRowTimeOut"] == 1:
        total_time *= 10
    return total_time

non_null_df["TotalTime"] = non_null_df.apply(get_total_time, axis=1)
non_null_df

,parameter,optimization_level,heuristic,solver,SavileRowTimeOut,SavileRowTotalTime,SolverNodes,SolverTotalTime,TotalTime
0,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,01_compact.eprime,kissat,0.0,4.164,688908.0,45.662,49.826
1,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,02_compact.eprime,chuffed,0.0,5.098,424.0,0.080,5.178
2,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,02_compact.eprime,kissat,0.0,4.292,4378.0,0.343,4.635
3,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,05_nochAllLevels_2.eprime,chuffed,0.0,6.179,339.0,0.050,6.229
4,params/generated/00032000e76ccda5fd02c1d8369f6...,O2,05_nochAllLevels_2.eprime,kissat,0.0,70.339,11399.0,0.101,70.440
...,...,...,...,...,...,...,...,...,...
69541,params/literature/ReginPuget4.param,O2,05_nochAllLevels_2.eprime,chuffed,0.0,3.261,194577775.0,3575.830,3579.091
69542,params/literature/ReginPuget4.param,O2,05_nochAllLevels_2.eprime,kissat,0.0,22.954,43147247.0,3600.140,3623.094
69543,params/literature/ReginPuget4.param,O2,06_chPrunedLevels.eprime,chuffed,0.0,34.462,113254117.0,3577.570,3612.032
69544,params/literature/ReginPuget4.param,O2,06_chPrunedLevels.eprime,kissat,0.0,1.268,40682889.0,3600.075,3601.343
69545,params/literature/ReginPuget4.param,O2,06_chPrunedLevels.eprime,kissat,0.0,2.422,201203166.0,3572.200,3574.622

In [35]:
def load_file(file_name):
    with open(file_name) as f:
        return f.read()
def get_dataset(df:pd.DataFrame):
    dataset = []
    for i in range(len(df)):
        row = df.iloc[i, :]
        dataset.append({
            "Parameters": load_file(row["parameter"]),
            "OptimizationLevel": row["optimization_level"],
            "Heuristic": row["heuristic"],
            "Solver": row["solver"],
            "Time": row["TotalTime"]
        })
    return dataset

dataset = get_dataset(non_null_df)

In [36]:
dataset[0]

{'Parameters': 'language Essence 1.3\n\nletting blksize_delta be\n        function(1 --> 3, 2 --> 3, 3 --> 3, 4 --> 3, 5 --> 3, 6 --> 3, 7 --> 3, 8 --> 3, 9 --> 3, 10 --> 3, 11 --> 3,\n                 12 --> 3, 13 --> 3, 14 --> 3, 15 --> 3, 16 --> 3, 17 --> 3, 18 --> 3, 19 --> 3)\nletting maxcars be\n        function(1 --> 10, 2 --> 9, 3 --> 6, 4 --> 10, 5 --> 10, 6 --> 10, 7 --> 10, 8 --> 9, 9 --> 10, 10 --> 10,\n                 11 --> 10, 12 --> 10, 13 --> 10, 14 --> 10, 15 --> 10, 16 --> 10, 17 --> 10, 18 --> 10, 19 --> 9)\nletting n_cars be 152\nletting n_classes be 2\nletting n_options be 19\nletting quantity be function(1 --> 76, 2 --> 76)\nletting usage be\n        relation((1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 8), (1, 9), (1, 10), (1, 11), (1, 12), (1, 13),\n                 (1, 14), (1, 15), (1, 16), (1, 17), (1, 18), (2, 7), (2, 19))\n$ Visualisation for usage\n$  1  1\n$  1  2\n$  1  3\n$  1  4\n$  1  5\n$  1  6\n$  1  8\n$  1  9\n$  1 10\n$  1 11\n$  1 12\n$  1 13\n$  1 14\n$  1 15\n$  1 16\n$  1 17\n$  1 18\n$  2  7\n$  2 19\n\n',
 'OptimizationLevel': 'O2',
 'Heuristic': '01_compact.eprime',
 'Solver': 'kissat',
 'Time': 49.826}