In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import os
import json
import matplotlib.pyplot as plt
import random
from sklearn.metrics import accuracy_score
from devtools import pprint 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import ParameterGrid
from helper import one_hot_encoding
random_state = 42
random.seed(random_state)

In [2]:
def train_validation_test_split(x, y, test_buckets = []):
    BUCKETS = 10

    N_ELEMENTS = len(x)

    BUCKET_SIZE = N_ELEMENTS // BUCKETS

    TEST_BUCKETS = 1


    x_local = x.copy()
    y_local = y.copy()
    x_test, y_test = [], []
    
    if len(test_buckets) == 0: 
        for _ in range(TEST_BUCKETS):
            idx = random.randint(0, BUCKETS)
            while idx in test_buckets:
                idx = random.randint(0, BUCKETS)
            test_buckets.append(idx)

    for bucket in test_buckets:
        idx = bucket * BUCKET_SIZE
        for _ in range(BUCKET_SIZE):
            x_test.append(x_local.pop(idx))
            y_test.append(y_local.pop(idx))

    train_elements = (len(y_local) // 10) * 9
    x_train = x_local[:train_elements]
    y_train = y_local[:train_elements]

    x_validation = x_local[train_elements:]
    y_validation = y_local[train_elements:]

    # buckets_x = [x.iloc[bucket * BUCKET_SIZE: (bucket + 1) * BUCKET_SIZE, :] for bucket in range(BUCKETS)]
    # buckets_y = [y[bucket * BUCKET_SIZE: (bucket + 1) * BUCKET_SIZE] for bucket in range(BUCKETS)]

    # x_train_validation = buckets_x[:TRAIN_VALIDATION_BUCKETS]
    # y_train_validation = buckets_y[:TRAIN_VALIDATION_BUCKETS]


    # x_train = x_train_validation[0] 
    # y_train = y_train_validation[0]
    # for i in range(1, TRAIN_SIZE):
    #     x_train = pd.concat([x_train, x_train_validation[i]])
    #     y_train += y_train_validation[i]
    # x_validation  = x_train_validation[TRAIN_SIZE]
    # y_validation = y_train_validation[TRAIN_SIZE]
    # for i in range(TRAIN_SIZE + 1, TRAIN_SIZE + VALIDATION_SIZE):
    #     x_validation = pd.concat([x_validation, x_train_validation[i]])
    #     y_validation += y_train_validation[i]

    # x_test = buckets_x[-TEST_BUCKETS]
    # y_test = buckets_y[-TEST_BUCKETS]
    # for i in range((BUCKETS - TEST_BUCKETS) + 1, BUCKETS):
    #     x_test = pd.concat([x_test, buckets_x[i]])
    #     y_test += buckets_y[i]
    
    return x_train, y_train, x_validation, y_validation, x_test, y_test

def get_time_matrix(shape:tuple, times:list[list[dict]]):
    time_matrix = np.zeros(shape)
    for i in range(len(times)):
        times_i = times[i]
        for j in range(len(times_i)):
            time_matrix[i,j] = times_i[j]["time"]
    return time_matrix

In [3]:
current_dir = "../features"
files = [f for f in os.listdir(current_dir) if os.path.isfile(os.path.join(current_dir, f))]
data = {}
for file in files:
    with open(current_dir + "/" + file) as f:
        data[file] = json.load(f)
splitted = [file.replace(".json", "").replace(".param", "").split("_") for file in files]
models = np.unique(["_".join(split[:-1]) for split in splitted]).tolist()
instances = np.unique([split[-1] for split in splitted]).tolist()
models = [mod for mod in models if "01" in mod]
instances_data = {}
for instance in instances:
    for model in models:
        instances_data[instance] = data[f"{model}_{instance}.param.json"]

In [4]:
f = open("../data/datasets/dataset.json")
dataset = json.load(f)
f.close()

In [5]:
for datapoint in dataset:
    instance = datapoint["instance"].split("/")[-1].replace(".param", "")
    datapoint["features"] = instances_data[instance]

In [6]:
data = pd.DataFrame(dataset)
data.head()

,combination,time,timeOut,instance,all_times,features
0,06_chPrunedLevels.eprime_cplex,2.466,0,params/generated/00032000e76ccda5fd02c1d8369f6...,"[{'time': 4.808999999999999, 'combination': '0...","{'c_avg_deg_cons': 7.4772, 'c_avg_dom_cons': 7..."
1,01_compact.eprime_or-tools1,1.200,0,params/generated/00078694bd51565b6a59a77ac27a3...,"[{'time': 1.445, 'combination': '01_compact.ep...","{'c_avg_deg_cons': 2.98652, 'c_avg_dom_cons': ..."
2,01_compact.eprime_cplex,4.468,0,params/generated/003fdfe3ec3b109ddf4ee4b64e995...,"[{'time': 7.547, 'combination': '01_compact.ep...","{'c_avg_deg_cons': 6.61241, 'c_avg_dom_cons': ..."
3,06_chPrunedLevels.eprime_or-tools1,2.206,0,params/generated/0041462199c3efeee8d75b1e7c58d...,"[{'time': 3.815, 'combination': '01_compact.ep...","{'c_avg_deg_cons': 6.64307, 'c_avg_dom_cons': ..."
4,01_compact.eprime_or-tools1,2.209,0,params/generated/005de4e641b1a31b5a79f20b98052...,"[{'time': 2.715, 'combination': '01_compact.ep...","{'c_avg_deg_cons': 4.77832, 'c_avg_dom_cons': ..."

In [7]:
X = data["features"]
X = [x for x in X.values]
y = [datapoint for datapoint in data["combination"].to_list()]
combinations = [d["combination"] for d in data["all_times"].tolist()[0]]
y = one_hot_encoding(y, combinations)
y  = [y_t.numpy() for y_t in y]

all_times = [datapoint["all_times"] for datapoint in dataset]
times_matrix = get_time_matrix((len(all_times), len(combinations)), all_times)
y_np = np.array(y)
majority_index = np.argmax([np.sum(y_np[:, i]) for i in range(len(combinations))])

bucket_size = len(X) // 10

In [8]:
stats = []

for test_bucket in range(10):
    X_train, y_train, X_validation, y_validation, X_test, y_test = train_validation_test_split(X,y, test_buckets=[test_bucket])
    X_train, X_validation, X_test = pd.DataFrame(X_train), pd.DataFrame(X_validation), pd.DataFrame(X_test)

    test_start = test_bucket * bucket_size
    test_idxs = [test_start + k for k in range(len(y_test))]
    train_val_idxs = [k for k in range(len(y)) if not k in test_idxs]
    train_elements = (len(train_val_idxs) // 10) * 9
    train_idxs = train_val_idxs[:train_elements]
    validation_idxs = train_val_idxs[train_elements:]

    assert len(test_idxs) == len(y_test)
    assert len(validation_idxs) == len(y_validation)
    assert len(train_idxs) == len(y_train)

    min_train = sum([min(times_matrix[i, :]) for i in train_idxs])
    min_val = sum([min(times_matrix[i, :]) for i in validation_idxs])
    min_test = sum([min(times_matrix[i, :]) for i in test_idxs])

    majority_train = sum([times_matrix[i, majority_index] for i in train_idxs])
    majority_val = sum([times_matrix[i, majority_index] for i in validation_idxs])
    majority_test = sum([times_matrix[i, majority_index] for i in test_idxs])

    sb_t = [sum([times_matrix[i, j] for i in train_idxs]) for j in range(len(combinations))]
    sb_v = [sum([times_matrix[i, j] for i in validation_idxs]) for j in range(len(combinations))]
    sb_te = [sum([times_matrix[i,j] for i in test_idxs]) for j in range(len(combinations))]

    sb_train = min(sb_t)
    sb_validation = min(sb_v)
    sb_test = min(sb_te)



    paramters_range = [{"criterion":["gini", "entropy", "log_loss"], "max_depth":[5,10,15,20,25,30], "min_samples_split": [2, 4, 8]}]
    parameters = list(ParameterGrid(paramters_range))

    scores = []
    e = lambda x: np.argmax(x)
    for i in range(len(parameters)):
        param = parameters[i]
        forest = RandomForestClassifier(**param,random_state=random_state)
        forest.fit(X_train, y_train)
        y_pred = forest.predict(X_validation)
        score = sum([times_matrix[idx, e(y_pred[i])] for idx in validation_idxs])
        scores.append(np.mean(score))

    best_tree = RandomForestClassifier(**parameters[np.argmin(scores)], random_state=random_state)
    best_tree.fit(X_train, y_train)
    y_test_predicted = best_tree.predict(X_test)
    y_train_predicted = best_tree.predict(X_train)
    y_val_predicted = best_tree.predict(X_validation)

    
    times_train = [times_matrix[train_idxs[i], e(y_train_predicted[i])] for i in range(len(y_train))]
    times_validation = [times_matrix[train_idxs[i], e(y_val_predicted[i])] for i in range(len(y_validation))]
    times_test = [times_matrix[train_idxs[i], e(y_test_predicted[i])] for i in range(len(y_test))]
    
    stats.append({
        "train_accuracy": round(accuracy_score(y_train, y_train_predicted) * 100, 2),
        "train_time": sum(times_train),
        "vb_train": min_train,
        "sb_min_time_train": sb_train,
        "sb_max_wins_train":majority_train,
        "validation_accuracy": round(accuracy_score(y_validation, y_val_predicted) * 100, 2),
        "validation_time": sum(times_validation),
        "vb_val": min_val,
        "sb_min_time_val": sb_validation,
        "sb_max_wins_val":majority_val,
        "test_accuracy": round(accuracy_score(y_test, y_test_predicted) * 100, 2),
        "test_time": sum(times_test),
        "vb_test": min_test,
        "sb_min_time_test": sb_test,
        "sb_max_wins_test":majority_test,
    })

In [9]:
pd.DataFrame(stats)

,train_accuracy,train_time,vb_train,sb_min_time_train,sb_max_wins_train,validation_accuracy,validation_time,vb_val,sb_min_time_val,sb_max_wins_val,test_accuracy,test_time,vb_test,sb_min_time_test,sb_max_wins_test
0,60.25,3232.513,2375.168,2622.540,3643.791,11.69,220.536,274.928,313.161,424.401,14.62,255.475,178.272,198.183,3067.242
1,59.02,3252.342,2387.977,2639.070,6535.319,18.18,3099.868,274.928,313.161,424.401,12.28,707.913,165.463,175.714,175.714
2,61.90,3051.241,2273.343,2523.797,6226.405,13.64,3095.718,274.928,313.161,424.401,12.28,710.149,280.097,296.926,484.628
3,60.97,3003.402,2240.654,2486.157,6177.592,12.34,3092.298,274.928,313.161,424.401,13.45,237.744,312.786,334.433,533.441
4,62.63,2991.094,2246.335,2484.083,6294.971,14.29,3089.885,274.928,313.161,424.401,14.04,701.662,307.105,336.571,416.062
5,62.05,2994.126,2227.196,2454.836,6215.781,14.94,3078.820,274.928,313.161,424.401,11.11,702.552,326.244,365.887,495.252
6,61.04,3033.219,2237.052,2465.282,6264.299,14.94,3093.583,274.928,313.161,424.401,14.62,703.356,316.388,355.441,446.734
7,62.91,2963.776,2244.414,2472.937,6211.823,14.94,3080.370,274.928,313.161,424.401,9.94,3137.129,309.026,347.786,499.210
8,61.54,3000.819,2228.064,2453.761,6170.990,12.99,3078.475,274.928,313.161,424.401,12.28,710.217,325.376,364.360,540.043
9,46.54,3518.905,2228.513,2454.886,6171.740,7.79,701.321,293.119,328.154,487.611,9.94,3121.113,306.736,348.557,476.083